### ISSUE TITLE
Genome sequencing costs

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#148]
Think this is a dataset worth of inclusion -- faster than Moore's law too!

## Sources

- http://www.genome.gov/sequencingcosts/ - this page has data from 2001 and some graphs. Data is in this excel sheet: http://www.genome.gov/pages/der/sequencing_costs_oct2015.xlsx
- pre 2001 ??

**Comment by rgrp** [comment]
@kiliakis another one for you to look at :-)

**Comment by kiliakis** [comment]
@rgrp okay, I'm working on it, I will post any useful info I find

**Comment by kiliakis** [comment]
@rgrp there are plots about genome sequencing cost per base: 
* http://synbiobeta.com/time-new-dna-synthesis-sequencing-cost-curves-rob-carlson/
* http://www.genomebiology.com/2010/11/5/207/figure/F2?highres=y

However, I can't really find the actual data. I will move on creating a dataset for these data.

**Comment by kiliakis** [comment]
@rgrp Datapackage is ready, here are the links:
* Actual data package: https://github.com/kiliakis/genome-sequencing-costs
* [Validation link] (http://data.okfn.org/tools/validate?url=https%3A%2F%2Fraw.github.com%2Fkiliakis%2Fgenome-sequencing-costs%2Fmaster%2Fdatapackage.json)
* [View link] (http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fkiliakis%2Fgenome-sequencing-costs)

In order to improve this datapackage, I would propose to add another csv file containing the logarithm of cost per Mb and cost per genome in order to display them in a logarithmic scale graph.

**Comment by pdehaye** [comment]
I just submitted a pull request, slightly changing the way you format the month. 

As for the view, I don't know. One way to do it directly is to compute the log directly, add that as a column, then build the view. That might be the best way, I can see how some would just want the log directly.

**Comment by pdehaye** [comment]
Added to the dataset registry

**Comment by rgrp** [comment]
@kiliakis  re view i would not compute log directly - we need support for that in the view stuff (not there right now) and so do not worry now - even if imperfect (cf my comment re new view stuff for you https://github.com/dataprotocols/dataprotocols/issues/77 /cc @pdehaye

**Comment by kiliakis** [comment]
@pdehaye This would probably fix the graph's view and make it more readable. However it would be a partial solution as in a log scale graph it is the axis scale that changes and not the actual values of the data series. 
@rgrp I will start familiarizing with vega-lite.

**Comment by pdehaye** [comment]
@kiliakis I have reopened this dataset because I just realised I did it wrong a month ago (sorry, still learning the ropes!). We need the dataset held by the datasets org to be the original repo, and yours (if you want to have one) to be a fork. From here, only you can proceed to correct the situation:
 1. go to https://github.com/datasets/genome-sequencing-costs/settings and delete that repo
 2. go to https://github.com/kiliakis/genome-sequencing-costs -> settings -> transfer ownership to the datasets organisation.

I could do 1. but not 2., and it's best if both are done in a close sequence.

This should do the trick!

**Comment by rgrp** [comment]
@kiliakis ping ;-)

**Comment by kiliakis** [comment]
@pdehaye, @rgrp oops, I missed that. Anyway, it looks like I don't have the permissions to modify a dataset, as the settings icon is missing. I think, I can only create new repositories and transfer ownership from my github to datasets. Here is my view:
![screenshot from 2016-02-08 12 39 28](https://cloud.githubusercontent.com/assets/11835649/12883494/117837dc-ce61-11e5-88cd-78f33d4f3cc7.png)

**Comment by pdehaye** [comment]
Then I will delete the datasets fork of your repo right now and you transfer ownership of your repo right after.

**Comment by pdehaye** [comment]
Done, please try transferring ownership.

**Comment by kiliakis** [comment]
Done

**Comment by pdehaye** [comment]
Great! Problem solved, now closing.
