### ISSUE TITLE
FIPS 10-4 Administrative Codes

### ISSUE THREAD

**Issue by rufuspollock** [datasets/registry#199]
https://en.wikipedia.org/wiki/FIPS_10-4

**Comment by zelima** [comment]
This can be used as source: http://efele.net/maps/fips-10/data/fips-414.txt
csv format:
```
country,region,code
ANTIGUA AND BARBUDA,,AC00
ANTIGUA AND BARBUDA,Barbuda dependency,AC01
ANTIGUA AND BARBUDA,Saint George parish,AC03
...
```

**Comment by AcckiyGerman** [comment]
Sometimes there are more then 2 lvl (country, region) division in the source, especially for United Kingdom:
**Country, London borough, metropolitan district, unitary authority, county (not country!), city corporation, ...** and it does matter I think.

My suggestion is to keep the original table structure:
* put the code column at the first.
* extract the division name
```csv
code, division, name
US00, country, UNITED STATES
US01, state, Alabama
....
UP00, country, UKRAINE
UP01, province_oblast', Cherkas'ka Oblast'
UP02, province_oblast', Chernihivs'ka Oblast'
UP11, autonomous republic_avtonomna respublika, Krym Avtonomna Respublika
...
```

**Comment by zelima** [comment]
@AcckiyGerman sounds great

**Comment by AcckiyGerman** [comment]
https://github.com/datasets/administrative-codes-FIPS-10-4  80% finished

**Comment by AcckiyGerman** [comment]
There is something wrong.
![pnf](https://user-images.githubusercontent.com/11707682/34275312-fea58c1c-e69c-11e7-970c-cc22719e2d9b.png)

**Comment by zelima** [comment]
@AcckiyGerman simple URL would be more useful instead. And I see it's there now: http://datahub.io/AcckiyGerman/region-codes 
Overall looks great, good job! Re-review for future: Would be easier for me to review PR instead of already pushed commits, but anyway, here are the commits I commented on:
* https://github.com/datasets/administrative-codes-FIPS-10-4/commit/f2ea5fa9c224edf6f8dbeff775437fc2f869951b
* https://github.com/datasets/administrative-codes-FIPS-10-4/commit/ec4c737a427f91dd95bf083d3e5a42c5c8000241
* https://github.com/datasets/administrative-codes-FIPS-10-4/commit/f863f8cd928bb71d3efbdf80d915b9ebf2fc5504

**Comment by AcckiyGerman** [comment]
@zelima the dataset is ready https://github.com/datasets/administrative-codes-FIPS-10-4
Please push it under the core user and close this issue.

**Comment by rufuspollock** [comment]
@AcckiyGerman can you please take care of pushing under core user.

I would also suggest that this dataset should just be fips-10-4.

**Comment by AcckiyGerman** [comment]
name is fixed. Publishing..

**Comment by AcckiyGerman** [comment]
FIXED
* data found and processed
* dataset is now here: https://github.com/datasets/fips-10-4
* and published here: https://datahub.io/core/fips-10-4
* https://github.com/datasets/registry/blob/master/core-list.csv is updated
